package com.example.hisab.model

/**
 * Represents a person with whom the user tracks financial transactions.
 *
 * @property id Unique identifier generated by SQLite.
 * @property name Display name of the person (e.g. "Sakshi", "Janvi").
 * @property createdAt Epoch timestamp (in milliseconds) when this person was added.
 * @property updatedAt Epoch timestamp (in milliseconds) when this record was last modified.
 * @property archived Flag indicating whether this person is hidden/archived.
 * @property currentBalancePaise The net unsettled balance for the current open period, in paise.
 *                               Positive: The person owes the user.
 *                               Negative: The user owes the person.
 *                               Zero: All accounts settled.
 */
data class Person(
    val id: Long = 0,
    val name: String,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val archived: Boolean = false,
    val currentBalancePaise: Long = 0L,
    val remoteId: String? = null
)
